# Generated by Django 2.1.1 on 2019-04-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20190402_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCouponOrdering',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupons.Coupon')),
                ('attributeChosen', models.CharField(choices=[('0', 'Coupon id'), ('1', 'valid_from'), ('2', 'valid_to'), ('3', 'active'), ('4', 'popularity')], max_length=1)),
                ('OrderOfCoupons', models.CharField(choices=[('0', 'Ascending'), ('1', 'Descending')], max_length=1)),
            ],
            bases=('coupons.coupon',),
        ),
    ]
