# Generated by Django 2.1.1 on 2019-02-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_myproductordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCategoryOrdering',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('attributeChosen', models.CharField(choices=[('0', 'Category id'), ('1', 'Name'), ('2', 'Num Of Products'), ('3', 'Popularity')], max_length=1)),
                ('OrderOfProducts', models.CharField(choices=[('0', 'Ascending'), ('1', 'Descending')], max_length=1)),
            ],
            bases=('shop.product',),
        ),
    ]
