# Generated by Django 2.1.1 on 2019-02-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190222_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProductSearch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('attributeChosen', models.CharField(choices=[('0', 'Product id'), ('1', 'Name')], max_length=1)),
                ('searchCriteria', models.CharField(max_length=200)),
            ],
            bases=('shop.product',),
        ),
    ]
