# Generated by Django 2.1.1 on 2019-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_myproductsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductsearch',
            name='searchCriteria',
            field=models.CharField(max_length=100),
        ),
    ]
