# Generated by Django 2.1.1 on 2019-04-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190304_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductordering',
            name='attributeChosen',
            field=models.CharField(choices=[('0', 'Product id'), ('1', 'Name'), ('2', 'Price'), ('3', 'Popularity of total quantity orderded'), ('4', 'Popularity of number of times ordered')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
