# Generated by Django 2.1.1 on 2019-03-14 09:27

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kuerzel', models.CharField(max_length=3)),
                ('kn_nr', models.CharField(max_length=5)),
                ('beschreibung', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
