# Generated by Django 2.1.1 on 2019-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190212_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('p', 'preparing'), ('b', 'baking'), ('r', 'ready')], default='p', help_text='Order status', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('s', 'in store'), ('d', 'delivery'), ('c', 'collection')], default='s', help_text='Order type', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'preparing'), ('b', 'baking'), ('r', 'ready')], default='p', max_length=1),
        ),
    ]
