# Generated by Django 2.1.1 on 2019-02-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190212_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='slug',
            new_name='orderslug',
        ),
    ]
