# Generated by Django 2.1.1 on 2019-02-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190212_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserOrdering',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Order')),
                ('attributeChosen', models.CharField(choices=[('0', 'Order id'), ('1', 'Customer id'), ('2', 'Date & TIme Created')], max_length=1)),
                ('OrderOfOrders', models.CharField(choices=[('0', 'Ascending'), ('1', 'Descending')], max_length=1)),
            ],
            bases=('orders.order',),
        ),
    ]
