# Generated by Django 2.1.1 on 2019-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190219_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
